### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-amikishyiev#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
1) Відомо, що безпечна клієнт-серверна взаємодія може забезпечуватися через наступні ключи: 
відкритий ключ клієнта, закритий ключ клієнта, відкритий ключ сервера, закритий ключ сервера. 
Вкажіть, будь ласка, який ключ вами було використано під час налаштування безпечного оновлення 
GitHub-репозиторію змінами з локального Git-репозиторію.

**Comment by Bloomberger** [comment]
Я використовував відкритий ключ клієнта. Тобто, створив сам ключ на локальному пристрої через команду ssh-keygen та додав в налаштуваннях акаунта GitHub, в розділі SSH and GPG keys.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
